### ISSUE TITLE
ValueError: not enough values to unpack

### ISSUE THREAD

**Issue by lucasjinreal** [xingyizhou/ExtremeNet#2]
```
Traceback (most recent call last):
  File "demo.py", line 268, in <module>
    image, ex, color_mask)
  File "/t/extremnet/utils/visualize.py", line 41, in vis_octagon
    img = vis_mask(img, mask, col)
  File "/t/extremnet/utils/visualize.py", line 22, in vis_mask
    mask.copy(), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by xingyizhou** [comment]
Hi,
  Thanks for running the code. It seems that you are using an older version of opencv, where cv2.findContours returns two values https://docs.opencv.org/2.4/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html#cv2.findContours. The opencv version used in this repo is 3.3.1 https://github.com/xingyizhou/ExtremeNet/blob/master/conda_packagelist.txt#L57, which returns 3 values for cv2.findContours https://docs.opencv.org/3.3.1/d4/d73/tutorial_py_contours_begin.html. Please follow the installation instruction when using this code.

**Comment by ausk** [comment]
@xingyizhou OpenCV change `cv2.findContours` in different versions. To make the code work in different versions, we can write like : `contours = cv2.findContours(...)[-2]`. And I create a pull for this https://github.com/xingyizhou/ExtremeNet/pull/22 .
