### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by wwetnaroh** [xingyizhou/ExtremeNet#39]
when I run tran.py ExtremeNet, the error occurs:
  Traceback (most recent call last):
  File "train.py", line 213, in <module>
    training_dbs  = [datasets[dataset](configs["db"], train_split) for _ in range(threads)]
  File "train.py", line 213, in <listcomp>
    training_dbs  = [datasets[dataset](configs["db"], train_split) for _ in range(threads)]
  File "/home/gxt/ExtremeNet/db/ead_extreme.py", line 68, in __init__
    self._load_data()
  File "/home/gxt/ExtremeNet/db/ead_extreme.py", line 77, in _load_data
    self._extract_data()
  File "/home/gxt/ExtremeNet/db/ead_extreme.py", line 133, in _extract_data
    if len(annotation["extreme_points"]) == 0:
KeyError: 'extreme_points'

**Comment by harry0308** [comment]
Did you solved this problem..?
