### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by zhuliqian** [xingyizhou/ExtremeNet#9]
(CornerNet) chase@zlq:~/ExtremeNet$ python demo.py
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    import torch
  File "/home/chase/anaconda3/envs/CornerNet/lib/python3.6/site-packages/torch/__init__.py", line 80, in <module>
    from torch._C import *
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

**Comment by xingyizhou** [comment]
Hi, 
  It seems that you haven't installed pytorch correctly. Do you have a GPU in your machine and have installed CUDA 9.0?

**Comment by zhuliqian** [comment]
thanks
Fixed! 
conda install -c anaconda cudatoolkit==9.0
